driver:
  name: vagrant

provisioner:
  name: shell
  data_path: .

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-10
    driver:
      box: williamtsoi/windows_10
    transport:
      name: winrm
      elevated: true
  - name: macos-sierra
    driver:
      box: jhcook/macos-sierra

suites:
  - name: default
